### ISSUE TITLE
Some suggestions to be closer to imgui coding style

### ISSUE THREAD

**Issue by ocornut** [dalerank/imspinner#1]
Great job on this!

Some suggestions

- It doesn't look like the bool return value are useful and they are inconsistent with how imgui uses bool. Maybe better to simply not return a value.
- Replace using `<array>` with regular C array.
- Use `ImFmod()` instead of `fmodf`, `ImAbs()`, `ImMax()`, `ImMin()`
- Remove the two static variables in `SpinnerRotateDots()`, use `ImGui::GetTime()`. For velocity may use window storage (map id to float) or reformulate the logic to be stateless (should be possible).
- Segments count can be calculated from size using the low-level helpers in imgui_draw.cpp

Structure (debatable)

- May make sense to move things into a `ImSpinner` namspace.
- May make sense to separate the code into a header file and a .cpp file, allowing the .cpp file to use `#include "imgui_internal.h"`. A single spot user can still include both files from same location. Header file makes API more discoverable.

Sorry for the spam, hope some of those are useful :)

**Comment by dalerank** [comment]
Fixed in 346ff892be3de6e0048d6a8e359d86003356eafc
Want to save simple oneheader style

**Comment by ocornut** [comment]
My suggestion to use GetTime() (same as g.Time, which was fine) was mostly for SpinnerRotateDots() where you manually maintained a time value. There are still uses of max(), fmaxf(), min().

**Comment by dalerank** [comment]
Fixed min/max in 76abeb653b2092b0cbd1420ad41845977784a604
