### ISSUE TITLE
Compilation errors if included in multiple translation units

### ISSUE THREAD

**Issue by Madman10K** [dalerank/imspinner#10]
First of all thanks for the spinners, they're great!

## About my device specs
Here is some information about the system I'm developing the application on:
1. OS: [Funtoo linux](https://funtoo.org/) on the "next" branch
2. GCC version: 11.3.0
3. GNU libc version: 2.33
4. Build system for the application: CMake using GCC and Ninja
5. C++ Standard used for compilation: C++ 20
6. Version of dear imgui: latest commit under the docking branch(synced to latest every 6 hours if new commits are available)

## About the application
The application I'm developing is a GUI Application framework based on dear imgui. Because libraries such as this are in wide use I decided it would provide good user experience to the future users of the framework to have useful libraries such as this one compile option away

To make handling of includes and other utility code such as settings serialization, all libraries get included into a master "module manager" header file. Because of this when the compile option for imspinner is enabled the header for imspinner gets included in about 13 translation units. When compiling I get a `multiple definitions error` like this one:
```
/home/i-use-gentoo-btw/Documents/UntitledImGuiFramework/Projects/ude-session-logout/Framework/Modules/Spinners/ThirdParty/imspinner/imspinner.h:883: multiple definition of `ImSpinner::SpinnerBarsScaleMiddle(char const*, float, ImColor const&, float, unsigned long)'; CMakeFiles/UntitledImGuiFramework.dir/Framework/Core/Components/Instance.cpp.o:/home/i-use-gentoo-btw/Documents/UntitledImGuiFramework/Projects/ude-session-logout/Framework/Modules/Spinners/ThirdParty/imspinner/imspinner.h:883: first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/UntitledImGuiFramework.dir/Source/MainView.cpp.o: in function `ImSpinner::SpinnerAngTwin(char const*, float, float, float, ImColor const&, ImColor const&, float, float, unsigned long)':
```
and that's basically the only issue with compiling the application

## How to resolve it
There are 2 ways to resolve this issue:
1. Prepend `inline` to the start of every function definition
1. Convert the library from a single header library to one with translation units

I have a working fork of the library that implements solution 1, because that's the simplest solution and because I want to be able to use the `IMGUI_API` macro to export the functions from a DLL if needed and that would mean that all functions will still need to be prefixed with something. 

If you're fine with using option 1 I will happily make a merge request :)

## Other compilation problems that might be good to fix
Even though this is not necessarily needed, it would be nice if `imspinner` also automatically included the `imgui.h` and `imgui_internal.h` files. Since these files are required by other libraries to be in the include path for the application so that the `#include "imgui.h"` call is successful from any header, it wouldn't be such a problem to also add these headers. This can be done like this:
```cpp
#if __has_include(<imgui.h>)
    #include "imgui.h"
    #include "imgui_internal.h"
#else
    #error "Couldn't find imgui.h in the header include path, please add it to the path!"
#endif
```
Of course not having these includes is an understandable design decision so if you decide you don't want code that includes them like the one above, I'd recommend to at least add an entry to the `README.md` that tells the user about this, this can either be text or just a link to #3

**Comment by dalerank** [comment]
Thanks, good idea

**Comment by dalerank** [comment]
Fixed, try it

**Comment by Madman10K** [comment]
Hello the commit fixed almost everything for me except the following functions:
1. `SpinnerBegin` at line 86
2. `demoSpinners` at line 2718

Additionally at line 2692 the `spinner_draw_funcs` array has to be marked inline because otherwise the lambdas produce the same linker error, line should look like this:
```cpp
struct SpinnerDraw { SpinnerTypeT type; void (*func)(const char *, const detail::SpinnerConfig &); } inline spinner_draw_funcs[e_st_count] = {
```

That's basically all that's left, thanks for the fast response :)
