### ISSUE TITLE
Annoucing Dear ImGui Bundle including imspinner and many others; with support for C++, Python and emscripten 

### ISSUE THREAD

**Issue by pthom** [dalerank/imspinner#11]
I'm happy to announce the first public release of Dear ImGui Bundle. Dear ImGui Bundle is a bundle for Dear ImGui, including many powerful libraries from its ecosystem. It enables to easily create ImGui applications in C++ *and* Python, under Windows, macOS, Linux, emscripten. It is aimed at application developers, researchers, and beginner developers who want to quickly get started.

imspinner is a included in the widgets provided with it.

* [Dear ImGui Bundle repo](https://github.com/pthom/imgui_bundle/)
* [Fully interactive online manual](https://traineq.org/ImGuiBundle/emscripten/bin/demo_imgui_bundle.html)
* [Specific annoucement for imspinner integration](https://github.com/pthom/imgui_bundle/discussions/71)

@dalerank: sorry to hijack the issues list for this, and feel to close this issue; as this is just for your information.  I informed @ocornut [yesterday](https://twitter.com/ocornut/status/1617963615503659008), and I plan to communicate about it in the [ImGui gallery](https://github.com/ocornut/imgui/issues/5886) in the next hours.

**Comment by dalerank** [comment]
Fine knobs, took it for pet project
![image](https://user-images.githubusercontent.com/918081/215062112-7a6ef72d-1880-4ee6-a1be-6a2562b5f310.png)
