### ISSUE TITLE
ImSpinner and Global Alpha Value

### ISSUE THREAD

**Issue by anzenchitai** [dalerank/imspinner#12]
Hello, I am enjoying ImSpinner so far but there is one slight problem.
For some reason, all ImSpinners seem to ignore the global alpha value.
I am working on a fade transition effect. When I use my fade functions,
-which manipulate the global alpha value- everything is affected by
the alpha change except for ImSpinners. I would really appreciate some
input on this. Thanks in advance and amazing job with ImSpinner.

**Comment by dalerank** [comment]
Thanks, will fix it

**Comment by dalerank** [comment]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/918081/215611579-47630fb2-5add-4aa5-8b01-c1e09a44ac0d.png">

**Comment by anzenchitai** [comment]
Thanks for the quick fix.
