### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by LionHackerman** [dalerank/imspinner#14]
When trying to compile, I get the following errors:
- [E0028] Expression must have a constant value (Line 46)
- [E0028] Expression must have a constant value (Line 47)
- [E0028] Expression must have a constant value (Line 48)
![image](https://user-images.githubusercontent.com/58070003/232008014-8ddb56e0-6b36-4475-9b9f-382a8545d15d.png)

**Comment by dalerank** [comment]
which platform? it works for msvc, Im not tried for another compilers

**Comment by dalerank** [comment]
Try static const ...
if it works I will fix it

**Comment by LionHackerman** [comment]
> which platform? it works for msvc, Im not tried for another compilers

x64 msvc.

**Comment by LionHackerman** [comment]
> Try static const ... if it works I will fix it

worked. thanks.
