### ISSUE TITLE
ISO-8859-1 encoding instead UTF-8

### ISSUE THREAD

**Issue by inobelar** [dalerank/imspinner#18]
I found, that currently it imposible to edit `imspiner.h` from browser, since it's non-utf-8:

![image](https://github.com/dalerank/imspinner/assets/20372668/d65ff9bd-b3df-482a-8d4d-a9f6cd9248fd)

Can you please change encoding for it? This will be very useful, because now, even to edit single line, we need to clone the entire repository to the local machine, then edit and commit & push changes, instead of doing it in one-click from the browser :)

**Comment by dalerank** [comment]
really strange, have no this error on my side. And ideas? (win10, last chrome)

**Comment by inobelar** [comment]
@dalerank I see this warning on 2 machines (both have different versions of `Kubuntu`); when try to 'edit' your repository and own fork; in both Firefox `114.0.2` and  Google Chrome `114.0.5735.133`. 

It seems that you don't see this warning because `ISO-8859-1` is the default locale on your system.

After searching for this issue, I found similar [StackOverflow question](https://stackoverflow.com/questions/52690220/stop-github-from-converting-my-windows-1252-txt-files-into-utf-8), so this is not only our bug. (In that question situation is even worse - GitHub says it's `ISO-8859-1` when file uploaded in `Windows 1252` encoding).

But even without GitHub web-ui, I checked that it's not lie (reference to `file -bi`: [here](https://www.baeldung.com/linux/find-file-encoding#usingfile)):
```shell
$ git clone https://github.com/dalerank/imspinner.git
$ cd ./imspinner/
$ file -bi ./imspinner.h 
text/x-c++; charset=iso-8859-1
```

----

Technically, all of this is not a "bug", I just want to **note** that if we want the sources to be easily accessible/editable around the whole world, they must be in `utf-8` encoding. Although on Windows, it looks like you have to put extra effort into this.

**Comment by dalerank** [comment]
fixed
