### ISSUE TITLE
lack of examples

### ISSUE THREAD

**Issue by Sultan-papagani** [dalerank/imspinner#23]
for a beginner, ImSpinner::demoSpinners(); is a bad example and its complicated.

**Comment by dalerank** [comment]
any suggestions?

**Comment by Sultan-papagani** [comment]
there could be a main.cpp with seperate spinner examples in it ?
for example i included the "imspinner.h" but cant accsess radius, thickness stuff and its not clear what arguments they take
![code_screenshot](https://github.com/dalerank/imspinner/assets/69393574/0212681e-727f-4d16-a93b-cbb48d3a469e)

**Comment by dalerank** [comment]
it one header lib, all you need simple packed in one file
yes you can, it declarative function interface, just read Aleksandrescu paper about declarative args using
spinners can be used differently with common function signature and declarative args, not all yet
just look below for clearly examples with using pure arguments

**Comment by dalerank** [comment]
wont fix
