### ISSUE TITLE
Spinner concept: HBO Max style

### ISSUE THREAD

**Issue by nitz** [dalerank/imspinner#6]
You seem to be adding lovely spinners regularly, so I figured I'd bring you a concept I noticed that you didn't quite have yet.

This is the spinner from HBO Max:

![hbo-max-spinner](https://user-images.githubusercontent.com/602691/203350315-dff4e706-3b20-4143-be40-c78ce28755be.gif)

Looks sorta like a combination between `ImSpinner::SpinnerFadeDots()` and `ImSpinner::SpinnerMovingDots()`, with the exception that the dots only move or fade, never both at the same time. Kinda gives it a nifty little "3D" effect like they're circling around something. (May be interesting if they scaled instead of faded, too!)

Feel free to close if you're not interested; thanks for all the lovely animations!

**Comment by dalerank** [comment]
Nice spinner, thanks. Will add this soon

**Comment by dalerank** [comment]
Done in 2553c1b

**Comment by nitz** [comment]
Fantastic -- I love the other you did based on it too that *really* gave it that 3D feeling. Great job!
