### ISSUE TITLE
git history is a bit heavy

### ISSUE THREAD

**Issue by pthom** [dalerank/imspinner#7]
Hi,

Many thanks for this beautiful library which I find actually useful. 
I'm working on integrating it into another open source library (https://github.com/pthom/imgui_bundle)

However, the git history of this repo is quite heavy, which makes it difficult to add it as a submodule.

````bash
> git clone https://github.com/dalerank/imspinner
Cloning into 'imspinner'...
remote: Enumerating objects: 303, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 303 (delta 31), reused 39 (delta 15), pack-reused 247
Receiving objects: 100% (303/303), 97.89 MiB | 9.94 MiB/s, done.
Resolving deltas: 100% (119/119), done.

(base) ➜  ramdisk cd imspinner
(base) ➜  imspinner git:(master) du -sh *
4.0K	LICENSE.txt
4.0K	README.md
104K	imspinner.h
1.8M	spinners.gif
(base) ➜  imspinner git:(master) du -sh .git
 98M	.git       # (!!!!)
````

Reducing the history size would mean rewriting the entire history and remove the commits that were adding large files which were then removed. Not very convenient, I guess. 

However, this is not a very concerning issue.  Feel free to close this if this is too much trouble.

Thanks and congrats again!

**Comment by dalerank** [comment]
Sorry, it because preview image, will look how to fix it

**Comment by dalerank** [comment]
Fixed

**Comment by pthom** [comment]
Thanks and have a great day!
