### ISSUE TITLE
unneccesary conversion of colors in default arguments

### ISSUE THREAD

**Issue by dcnieho** [dalerank/imspinner#8]
The library has many instances of spinner with functions signatures such as this:
```
void SpinnerAng(const char *label, float radius, float thickness, const ImColor &color = 0xffffffff, const ImColor &bg = 0xffffff80, float speed = 2.8f, float angle = IM_PI)
```
I want to highlight the arguments like `const ImColor &color = 0xffffffff`. It is nice that you accept an `ImColor` and not an `ImU32`, as that gives much flexibility to users. However, using an unsigned int as default value triggers unnecessary conversion since ImColor stores colors internally as four floats. I propose to change these to signatures like `const ImColor &color = {1.f,1.f,1.f,1.f}`, which is slightly less compact but saves both the bitshift and division needed to perform the color conversion. I have looked through, and all the default color values can be types exactly with either `1.f` or `.5f`, thats the only default component intensities specified in the library.

This may seem a change with small benefit for C++ users. However, I am helping @pthom out a bit with a project that provides an automatically generated [python wrapper for imgui](https://github.com/pthom/imgui_bundle) and popular imgui libraries including imspinner. There we ran into [an issue with these default parameters](https://github.com/pthom/imgui_bundle/issues/53). Long story short, we had to solve it by manually changing the generated code, which is a maintenance headache. So while it is a minor optimization for C++ users, it would have a large impact on us.

I am of course prepared to send a pull request implementing these changes. Would you be happy to receive that?

**Comment by dalerank** [comment]
Sorry for late, please prepare PR, I will accept it

**Comment by dalerank** [comment]
also if u interest, I add another animation library for imgui
https://github.com/dalerank/imlottie

**Comment by dcnieho** [comment]
@dalerank: cool, will do.
@pthom: see imlottie. Looks really cool!

**Comment by dalerank** [comment]
Fixed

**Comment by pthom** [comment]
Thanks to both of you :-)
